app/Http/routes.php
		Route::get('admin-data','AdminDashboardController@getData');
		Route::post('user-data','AdminDashboardController@postUserData');
		Route::post('admin-data/logs','AdminDashboardController@getLogData');

		Route::post('password/email','UserPasswordController@postEmail');

		Route::post('updates','UpdatesController@getUpdates');
		Route::post('updates/create','UpdatesController@create');

		Route::post('log','UserLogController@create');

		Route::post('getlog','UserLogController@getLog');

		Route::post('leave','LeaveController@create');
		Route::post('admin-leave','LeaveController@adminLeave');
		Route::post('leave-status','LeaveController@status');
		Route::post('leave-delete','LeaveController@LeaveDelete');

		Route::post('leave-report','LeaveController@getLeave');

		Route::get('holidays','HolidayController@index');

		Route::post('change-password','ChangePasswordController@index');

		Route::post('image-upload','ImageUploadController@index');

		Route::post('set-reminder','UserLogController@setReminder');
		Route::post('new-reminder','UserLogController@newReminder');
		Route::post('userlog','UserLogController@userLog');
		Route::post('settings','UserLogController@setting');

		Route::post('quiz','QuizController@getQuiz');
		Route::post('store-quiz-answer','QuizController@storeQuizAnswer');
		Route::post('quiz-list','QuizController@quizList');
		Route::post('quiz-leaderboard','QuizController@getLeaderBoard');
		Route::post('quiz-activityboard','QuizController@getActivityBoard');

		Route::get('user-birthday','UsersController@userBirthday');
		#---------------------------Routes For ATS----------------------
		Route::post('ats-instantid','ATSInstantIdController@store');
		Route::post('send-notification','ATSInstantIdController@sendMessage');

	});
});

Route::group(['middleware' => 'web'], function() {

	Route::get('login',[
		'as' => 'login',
		'uses' => 'Auth\AuthController@getLogin'
	]);

	Route::post('login',[
		'as' => 'user.login',
		'uses' => 'Auth\AuthController@postLogin'
	]);

	Route::get('logout','Auth\AuthController@getLogout');

	Route::get('/', function () {

		if( Auth::check() ) {
            return redirect()->route('dashboard.admin');
        }

		return view('auth.login');
	});

	//Route::get('verify/{code}', 'Auth\AuthController@accountIsActive');

	Route::post('/trash',[
		'as' => 'user.trash',
		'uses' => 'TimeloggerController@trash'
	]);
	Route::get('recyclebin',[
		'as' => 'user.recyclebin',
		'uses' => 'TimeloggerController@recyclebin'
	]);

	Route::get('restore/{id}',[
		'as' => 'user.restore',
		'uses' => 'TimeloggerController@restore'
	]);
	Route::get('user/delete/{id}',[
		'as'=> 'user.destroy',
		'uses'=>'TimeloggerController@destroy'
	]);

	Route::get('password/email','Auth\PasswordController@getEmail');
	Route::post('password/email','Auth\PasswordController@postEmail');
	Route::get('password/reset/{token}','Auth\PasswordController@getReset');
	Route::post('password/reset','Auth\PasswordController@postReset');

	Route::get('denied',[
		'as' => 'user.denied',
		'uses' => function(){
			return 'denied';
		}
	]);

	/*User authinticate*/
	Route::group(array('middleware' => ['auth']), function(){

			Route::get('dashboard',[
					'as'=>'dashboard.admin',
					'uses'=>'TimeloggerController@admin'
			]);

			Route::post('get-selected-pemission',array(
					'as' => 'selectpermission.get',
					'uses' => 'UserPermissionController@getSelectedPermissions'
			));
		//karishma	
		Route::post('leaves/delete',[
				'as'   => 'leaves.delete',
				'uses' => 'LeavesController@destroy'
			]);
		Route::post('leave/status','LeavesController@leaveStatus')->name('leave.status');
		Route::post('notification/isread','LeavesController@notificationIsread')->name('notification.isread');
		Route::post('notification/isview','LeavesController@notificationIsview')->name('notification.isview');
		Route::get('logs/exportlogs/{id}/{month}/{year}',array(
					'as' => 'logs.exportlogs',
					'uses' => 'ShowController@exportlogs'
				));
		Route::get('logs/alluserexportlogs/{id}/{month}/{year}',array(
					'as' => 'logs.alluserexportlogs',
					'uses' => 'ShowController@allUserExportLogs'
				));
		Route::get('workingdays',array(
					'as' => 'admin.workingdays',
					'uses' => 'WorkingDaysController@index'
				));
		Route::post('workingdays',array(
					'as' => 'admin.workingdays',
					'uses' => 'WorkingDaysController@workingdays'
				));
		Route::post('store/workingdays',array(
					'as' => 'admin.store.workingdays',
					'uses' => 'WorkingDaysController@storeworkingdays'
				));
		Route::get('user/profile/upload-photo/{id?}', array(
			'as'	=> 'user.profile.upload.get',
			'uses'	=> 'TimeloggerController@getUploadProfilePhoto'
		));

		Route::post('user/profile/upload-photo', array(
			'as'	=> 'user.profile.upload.post',
			'uses'	=> 'TimeloggerController@postUploadProfilePhoto'
		));

		Route::get('/user/profile/crop-photo', array(
			'as'	=> 'user.profile.photo.crop.get',
			'uses'  => 'TimeloggerController@getCropProfilePhoto'
		));

		Route::post('/user/profile/crop-photo', array(
			'as'	=> 'user.profile.photo.crop.post',
			'uses'  => 'TimeloggerController@postCropProfilePhoto'
		));
		Route::post('/user/deactive', array(
			'as'	=> 'user.deactive',
			'uses'  => 'TimeloggerController@userDeactive'
		));
		Route::post('/leaves/chart', array(
			'as'	=> 'dashboard.leaves.chart',
			'uses'  => 'TimeloggerController@getChart'
		));
		Route::post('/leaves/secondchart', array(
			'as'	=> 'dashboard.leaves.secondchart',
			'uses'  => 'TimeloggerController@getSecondChart'
		));
		Route::post('workingdays/hours',array(
			'as' => 'admin.workingdays.hours',
			'uses' => 'WorkingDaysController@workingdaysHours'
		));
		Route::resource('services','ServicesController',['except'=>['delete','show']]);
		Route::post('services/delete','ServicesController@delete')->name('services.delete');
		Route::post('category/store','ServicesController@categoryStore')->name('category.store');
		Route::get('weeklylogs',array(
			'as' => 'admin.weeklylogs',
			'uses' => 'WeeklyLogsController@weeklyLogs'
		));

		
		//end karishma
		//rushik
		Route::resource('/holiday-master','HolidaysMasterController',['except'=>['delete','show']]);
		Route::post('/holiday-master/delete','HolidaysMasterController@delete')->name('holiday-master.delete');
		Route::resource('/holiday-year','HolidayYearController',['except'=>['delete','show']]);
		Route::post('/holiday-year/delete','HolidayYearController@delete')->name('holiday-year.delete');
		Route::get('holiday/upload-photo', array(
					'as'	=> 'holiday.upload.get',
					'uses'	=> 'HolidaysMasterController@getUploadProfilePhoto'
				));
		Route::post('holiday/upload-photo', array(
					'as'	=> 'holiday.upload.post',
					'uses'	=> 'HolidaysMasterController@postUploadProfilePhoto'
				));
		Route::get('/holiday/crop-photo', array(
					'as'	=> 'holiday.photo.crop.get',
					'uses'  => 'HolidaysMasterController@getCropProfilePhoto'
				));
		Route::post('/holiday/crop-photo', array(
					'as'	=> 'holiday.photo.crop.post',
					'uses'  => 'HolidaysMasterController@postCropProfilePhoto'
				));
		Route::post('/dashboard/leaves/store', array(
				'as'	=> 'dashboard.leaves.store',
				'uses'  => 'LeavesController@leavestore'
			));
		Route::post('/dashboard/leaves/second/store', array(
				'as'	=> 'dashboard.leaves.second.store',
				'uses'  => 'LeavesController@leavesecondstore'
			));
		Route::post('/dashboard/leaves/third/store', array(
				'as'	=> 'dashboard.leaves.third.store',
				'uses'  => 'LeavesController@leavethirdstore'
			));
		Route::post('/user/checkin', array(
				'as'	=> 'user.checkin',
				'uses'  => 'TimeloggerController@checkIn'
			));
		Route::resource('assets','AssetsController',['except'=>['delete','show']]);
		Route::post('assets/delete','AssetsController@delete')->name('assets.delete');
		Route::resource('assets/master','AssetsMasterController',['except'=>['delete','show']]);
		Route::post('assets/master/delete','AssetsMasterController@delete')->name('assets.master.delete');			
		//end rushik
		Route::group(array('middleware'=> ['acl']),function(){
				

				Route::resource('/user','TimeloggerController',['except'=>['destroy']]);
				Route::resource('/leaves','LeavesController',['except'=>['show']]);
				Route::resource('/holiday','HolidaysController',['except'=>['destroy']]);
				

				Route::get('holiday/delete/{id}',[
					'as'=> 'holidays.delete',
					'uses'=>'HolidaysController@destroy'
				]);

				Route::get('leaves/{user_id}/create',array(
					'as' => 'user.leaves.create',
					'uses' => 'LeavesController@userCreate'
				));

				Route::get('leaves/{user_id}/store',array(
					'as' => 'user.leaves.store',
					'uses' => 'LeavesController@userStore'
				));

				Route::get('quiz-delete/{quiz_id}',array(
					'as' => 'quiz.delete',
					'uses' => 'QuizController@delete'
				));

				Route::get('quiz-send/{quiz_id}',array(
					'as' => 'quiz.send',
					'uses' => 'QuizController@send'
				));

				Route::resource('quiz','QuizController',['except'=>['destroy','show']]);
				
				
				Route::get('logs',[
					'as' => 'logs.index',
					'uses' => 'LogController@index'
				]);
				Route::resource('userpermission','UserPermissionController');

				Route::get('profile',[
					'as' =>'show.user',
					'uses' =>'ShowController@profile'
				]);

				Route::get('logs/{id}',[
					'as'=>'show.logs',
					'uses'=>'ShowController@log'
				]);

				Route::get('leaves/{id}',[
					'as'=>'show.leaves',
					'uses'=>'ShowController@leave'
				]);

				Route::get('Leave/{id}/approve',[
					'as' => 'leaves.approve',
					'uses' => 'LeavesController@approveLeave'
				]);

				Route::post('Leave/{id}/Approve',[
					'as'  => 'sendmail.approve',
					'uses'  =>'LeavesController@approvemail']);

				Route::post('Leave/{id}/Reject',[
					'as'  => 'sendmail.reject',
					'uses'  =>'LeavesController@rejectemail'
				]);

				// Route::post('leaves/delete',[
				// 	'as'   => 'leaves.destroy',

app/Models/Permission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Permission extends Model{

	public $table = 'permission';
	public $fillable = ['route','section','description'];
	public $timestamps = false;

	
}

resources/views/permission/create.blade.php
@extends('layout.layout')
@section('content')
<div class="page-title">
        <div>
          <h1>Permission</h1>
            <ul class="breadcrumb side">
              <li><i class="fa fa-home fa-lg"></i></li>
              <li>Create</li>
           </ul>
        </div>
</div>
<div class="clearix"></div>
    @include('partials.alert')
    <div class="row">
    	<div class="col-md-12">
        	<div class="card">
        		<h3 class="card-title">Create</h3>
     			<div class="card-body">
      				<?= Form::open(array('url' => route('userpermission.store') ,'class' => 'form-horizontal' ,'files' => true)) ?>
          				<div class="form-group">
                			<label class="control-label col-sm-2" for="inputFull Name">User</label>
                			<div class="col-sm-8">
            					<label><?= Form::select('user_id',[''=>'select'] + $users,old('user_id'),['class' => 'form-control','id' => 'userchange']) ?></label>
                                <span class="help-inline text-danger">{{ $errors->first('user_id') }}</span>
                            </div>
    					</div>
    	                <div class="form-group">
                            <label class="control-label col-sm-2" for="inputFull Name">Permission</label>
                            <div class="animated-checkbox" style="margin-bottom:10px;">
                                <label style="margin: 11px 19px;"><input type="checkbox" id="selectall"><span class="label-text">Select All</span></label>
                                <span class="help-inline text-danger">{{ $errors->first('permissions') }}</span>
                            </div>
                            <div class="row">
        					<div class="col-sm-offset-2 col-sm-10">
                                    @foreach($secPermissions as $sectionName => $secByPermission)
                                    <div class="col-sm-12 permission-section">
                                        <div class="panel-group" id="accordion">
                                            <div class="panel panel-default">
                                                <div class="panel-heading">
                                                    <a class="collapsed panellink-title" data-toggle="collapse" data-parent="#accordion" href="#<?= $sectionName ?>"><?= ucfirst($sectionName) ?></a>
                                                    <div class="animated-checkbox" style="margin-bottom:0px;float: right;">
                                                        <label><input type="checkbox" id="" class="section_selectall" data="<?= $sectionName?>"><span class="label-text">Select All</span></label>
                                                    </div>
                                                </div>
                                                <div class="panel-collapse collapse" id="<?= $sectionName ?>">
                                                    @foreach($secByPermission as $permission)
                                                        <div class="panel-body">
                                                            <div class="animated-checkbox">
                                                                <label>
                                                                    <input type="checkbox" name="permissions[]" id="<?= $permission['id']; ?>" value="<?= $permission['id']; ?>">
                                                                    <span class="label-text"><?= $permission['description']; ?></span>
                                                                </label>
                                                            </div>
                                                        </div>
                                                    @endforeach
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    @endforeach
                                </div>
    						</div>
    					</div>
       	  				<div class="form-group">
          					<div class="col-md-8 col-md-offset-2">
            					<button type="submit" class="btn btn-primary">Submit</button>
          					</div>
          				</div>
      				{!! Form::close() !!}
      			</div>
        	</div>
      	</div>
    </div>
</div>

@stop
@section('style')
    <?= Html::style('asset/css/new_dashboard.css') ?>
@stop
@section('script')
<!-- <script src="https://code.jquery.com/jquery-1.10.2.js"></script> -->
<script>
    jQuery(document).ready(function() {
        $('form').submit(function(){
            $(this).find('button:submit').html('<span><i class="fa fa-spinner fa-spin"></i>Please Wait....</span>').prop('disabled', true);
        });
        $('.section_selectall').on('change',function(){
            var isChecked = $(this).is(':checked');
            var id = $(this).attr('data');
            if (isChecked) {
                $('#'+id+' input:checkbox').prop('checked',true);
            } else {
                $('#'+id+' input:checkbox').prop('checked',false);
            }
        });
        $('#selectall').on('change',function(){
            var isChecked = $(this).is(':checked');
            console.log(isChecked);

            if (isChecked) {
                $('input:checkbox').prop('checked',true);
            } else {
                $('input:checkbox').prop('checked',false);
            }
        });

        $('#userchange').on('change',function(){

            var userId = $(this).val();

            if (userId == null && userId == '') {
                return;
            }

            $.ajax({
                url: '<?= route('selectpermission.get') ?>',
                type: 'json',
                method: 'post',
                data: {'user_id': userId,'_token': '<?= csrf_token() ?>' },
                beforeSend: function(){
                    $('input:checkbox').removeAttr('checked');
                },
                complete: function(){

                },
                success: function(resp){
                    if( ! resp.success ) {
                        return;
                    }
                    for (var i = 0; i < resp.user_permissions.length; i++) {
                        var seletedValue = resp.user_permissions[i].permission_id;
                        $('#'+seletedValue).prop('checked',true);
                    }
                }
            })
        });

    });
</script>
@include('partials.alert')
@stop