app/Http/routes.php
<?php
// use Hash;
Route::get('/hash/{str}', function($str) {
 	return Hash::make($str);
});

Route::get('testmail',function(){
	Mail::send('emails.test',['hello'],function($message){
		$message->from('noreply@thinktanker.in');
		$message->to('utsav@yopmail.com')->subject('nothing');
	});
});

Route::group(['middleware' => 'api'], function() {

	Route::get('api/v1.1/test1',function(){
		$push = PushNotification::app('appNameAndroid')
											->to('f1xKR2wimTk:APA91bEaj07KcoQFKTtnUesRvefwIYrhVROj00N1rM2UI4x597X-9RcloCV9vs__9i_TK992t2lg9Qb0i2ud-t8wSj5dOmlWOCGsJ_dXoh-FqSitupYhs9G_JxP7OmYBzpHhOLDR7j8g')
											->send('hello there');
		// dd($push);
	});

	Route::post('api/v1.1/oauth/access_token', function() {
		return response()->json(Authorizer::issueAccessToken());
	});


	Route::group(['namespace' => 'api'],function(){

		Route::get('register/verify/{confirm_code}','UsersController@confirm');

		Route::get('password/reset/{token}', 'UserPasswordController@getReset');
		// Route::get('/hash/{str}', function($str) {
		// 	return Hash::make($str);
		// });

		Route::post('amts/email','ATSInstantIdController@confirmEmail');
		Route::post('password/reset', 'UserPasswordController@postReset');
		Route::post('database-insert','UserPasswordController@DatabaseInsert');
		Route::post('location-get','UserPasswordController@LocationGet');
		Route::post('location-current','UserPasswordController@LocationCurrent');
		Route::post('location-latest','UserPasswordController@LatestLocation');
		Route::post('location-push','UserPasswordController@LocationPush');
		Route::post('configuration-push','UserPasswordController@ConfigurationPush');
		Route::get('configuration-get','UserPasswordController@ConfigurationGet');
		Route::post('edit-user','UserPasswordController@EditUSer');
		
	});

	Route::group(['prefix' => 'api/v1.1','middleware' => 'oauth', 'namespace' => 'api'] ,function(){

		Route::post('dashboard','LeaveController@dashboard');
		Route::post('register','UsersController@store');
		Route::post('user-update','UsersController@update');
		Route::get('user-list','UsersController@userList');

		Route::post('login','UsersController@login');
		Route::post('profile','UsersController@showProfile');
		Route::post('logout','UsersController@logout');

		Route::get('admin-data','AdminDashboardController@getData');
		Route::post('user-data','AdminDashboardController@postUserData');
		Route::post('admin-data/logs','AdminDashboardController@getLogData');

		Route::post('password/email','UserPasswordController@postEmail');

		Route::post('updates','UpdatesController@getUpdates');
		Route::post('updates/create','UpdatesController@create');

		Route::post('log','UserLogController@create');

		Route::post('getlog','UserLogController@getLog');

		Route::post('leave','LeaveController@create');
		Route::post('admin-leave','LeaveController@adminLeave');
		Route::post('leave-status','LeaveController@status');
		Route::post('leave-delete','LeaveController@LeaveDelete');

		Route::post('leave-report','LeaveController@getLeave');

		Route::get('holidays','HolidayController@index');

		Route::post('change-password','ChangePasswordController@index');

		Route::post('image-upload','ImageUploadController@index');

		Route::post('set-reminder','UserLogController@setReminder');
		Route::post('new-reminder','UserLogController@newReminder');
		Route::post('userlog','UserLogController@userLog');
		Route::post('settings','UserLogController@setting');

		Route::post('quiz','QuizController@getQuiz');
		Route::post('store-quiz-answer','QuizController@storeQuizAnswer');
		Route::post('quiz-list','QuizController@quizList');
		Route::post('quiz-leaderboard','QuizController@getLeaderBoard');
		Route::post('quiz-activityboard','QuizController@getActivityBoard');

		Route::get('user-birthday','UsersController@userBirthday');
		#---------------------------Routes For ATS----------------------
		Route::post('ats-instantid','ATSInstantIdController@store');
		Route::post('send-notification','ATSInstantIdController@sendMessage');

	});
});

Route::group(['middleware' => 'web'], function() {

	Route::get('login',[
		'as' => 'login',
		'uses' => 'Auth\AuthController@getLogin'
	]);

	Route::post('login',[
		'as' => 'user.login',
		'uses' => 'Auth\AuthController@postLogin'
	]);

	Route::get('logout','Auth\AuthController@getLogout');

	Route::get('/', function () {

		if( Auth::check() ) {
            return redirect()->route('dashboard.admin');
        }

		return view('auth.login');
	});

	//Route::get('verify/{code}', 'Auth\AuthController@accountIsActive');

	Route::post('/trash',[
		'as' => 'user.trash',
		'uses' => 'TimeloggerController@trash'
	]);
	Route::get('recyclebin',[
		'as' => 'user.recyclebin',
		'uses' => 'TimeloggerController@recyclebin'
	]);

	Route::get('restore/{id}',[
		'as' => 'user.restore',
		'uses' => 'TimeloggerController@restore'
	]);
	Route::get('user/delete/{id}',[
		'as'=> 'user.destroy',
		'uses'=>'TimeloggerController@destroy'
	]);

	Route::get('password/email','Auth\PasswordController@getEmail');
	Route::post('password/email','Auth\PasswordController@postEmail');
	Route::get('password/reset/{token}','Auth\PasswordController@getReset');
	Route::post('password/reset','Auth\PasswordController@postReset');

	Route::get('denied',[
		'as' => 'user.denied',
		'uses' => function(){
			return 'denied';
		}
	]);

	/*User authinticate*/
	Route::group(array('middleware' => ['auth']), function(){

			Route::get('dashboard',[
					'as'=>'dashboard.admin',
					'uses'=>'TimeloggerController@admin'
			]);

			Route::post('get-selected-pemission',array(
					'as' => 'selectpermission.get',
					'uses' => 'UserPermissionController@getSelectedPermissions'
			));
		//karishma	
		Route::post('leaves/delete',[
				'as'   => 'leaves.delete',
				'uses' => 'LeavesController@destroy'
			]);
		Route::post('leave/status','LeavesController@leaveStatus')->name('leave.status');
		Route::post('notification/isread','LeavesController@notificationIsread')->name('notification.isread');
		Route::post('notification/isview','LeavesController@notificationIsview')->name('notification.isview');
		Route::get('logs/exportlogs/{id}/{month}/{year}',array(
					'as' => 'logs.exportlogs',
					'uses' => 'ShowController@exportlogs'
				));
		Route::get('logs/alluserexportlogs/{id}/{month}/{year}',array(
					'as' => 'logs.alluserexportlogs',
					'uses' => 'ShowController@allUserExportLogs'
				));
		Route::get('workingdays',array(
					'as' => 'admin.workingdays',
					'uses' => 'WorkingDaysController@index'
				));
		Route::post('workingdays',array(
					'as' => 'admin.workingdays',
					'uses' => 'WorkingDaysController@workingdays'
				));
		Route::post('store/workingdays',array(
					'as' => 'admin.store.workingdays',
					'uses' => 'WorkingDaysController@storeworkingdays'
				));
		Route::get('user/profile/upload-photo/{id?}', array(
			'as'	=> 'user.profile.upload.get',
			'uses'	=> 'TimeloggerController@getUploadProfilePhoto'
		));

		Route::post('user/profile/upload-photo', array(
			'as'	=> 'user.profile.upload.post',
			'uses'	=> 'TimeloggerController@postUploadProfilePhoto'
		));

		Route::get('/user/profile/crop-photo', array(
			'as'	=> 'user.profile.photo.crop.get',
			'uses'  => 'TimeloggerController@getCropProfilePhoto'
		));

		Route::post('/user/profile/crop-photo', array(
			'as'	=> 'user.profile.photo.crop.post',
			'uses'  => 'TimeloggerController@postCropProfilePhoto'
		));
		Route::post('/user/deactive', array(
			'as'	=> 'user.deactive',
			'uses'  => 'TimeloggerController@userDeactive'
		));
		Route::post('/leaves/chart', array(
			'as'	=> 'dashboard.leaves.chart',
			'uses'  => 'TimeloggerController@getChart'
		));
		Route::post('/leaves/secondchart', array(
			'as'	=> 'dashboard.leaves.secondchart',
			'uses'  => 'TimeloggerController@getSecondChart'
		));
		Route::post('workingdays/hours',array(
			'as' => 'admin.workingdays.hours',
			'uses' => 'WorkingDaysController@workingdaysHours'
		));
		Route::resource('services','ServicesController',['except'=>['delete','show']]);
		Route::post('services/delete','ServicesController@delete')->name('services.delete');
		Route::post('category/store','ServicesController@categoryStore')->name('category.store');
		Route::get('weeklylogs',array(
			'as' => 'admin.weeklylogs',
			'uses' => 'WeeklyLogsController@weeklyLogs'
		));

		
		//end karishma
		//rushik
		Route::resource('/holiday-master','HolidaysMasterController',['except'=>['delete','show']]);
		Route::post('/holiday-master/delete','HolidaysMasterController@delete')->name('holiday-master.delete');
		Route::resource('/holiday-year','HolidayYearController',['except'=>['delete','show']]);
		Route::post('/holiday-year/delete','HolidayYearController@delete')->name('holiday-year.delete');
		Route::get('holiday/upload-photo', array(
					'as'	=> 'holiday.upload.get',
					'uses'	=> 'HolidaysMasterController@getUploadProfilePhoto'
				));
		Route::post('holiday/upload-photo', array(
					'as'	=> 'holiday.upload.post',
					'uses'	=> 'HolidaysMasterController@postUploadProfilePhoto'
				));
		Route::get('/holiday/crop-photo', array(
					'as'	=> 'holiday.photo.crop.get',
					'uses'  => 'HolidaysMasterController@getCropProfilePhoto'
				));
		Route::post('/holiday/crop-photo', array(
					'as'	=> 'holiday.photo.crop.post',
					'uses'  => 'HolidaysMasterController@postCropProfilePhoto'
				));
		Route::post('/dashboard/leaves/store', array(
				'as'	=> 'dashboard.leaves.store',
				'uses'  => 'LeavesController@leavestore'
			));
		Route::post('/dashboard/leaves/second/store', array(
				'as'	=> 'dashboard.leaves.second.store',
				'uses'  => 'LeavesController@leavesecondstore'
			));
		Route::post('/dashboard/leaves/third/store', array(
				'as'	=> 'dashboard.leaves.third.store',
				'uses'  => 'LeavesController@leavethirdstore'
			));
		Route::post('/user/checkin', array(
				'as'	=> 'user.checkin',
				'uses'  => 'TimeloggerController@checkIn'
			));

app/Models/HolidayMaster.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class HolidayMaster extends Model
{
    public $table = 'holiday_master';

	public $fillable = ['id','title'];
}

resources/views/holiday-master/create.blade.php
@extends('layout.layout')
@section('content')
<style type="text/css">
    .avtar{
    background-color: #fff;
    padding:20px 0;
    }
    .avtar button.btn-primary {
    float: none;
    width: 80%;
    margin: 20px auto;
    }
    .avtar form {
    float: none;
    width: 90%;
    margin: auto;
    }
    .profile-detail{
    width:100%;
    background-color: #fff;
    padding:20px 0;
    }
    .profile-detail .dl-horizontal, .profile-detail .dd-horizontal {
    margin: 10px 0;
    }
    .profile-detail label {
    float: right;
    font-size: 16px;
    margin: 19px 0;
    }
    .profile-detail .form-control {
    float: left;
    width: 98%;
    margin: 10px 0;
    }
    .profile-detail textarea {
    width: 98%;
    }
    .profile-detail button {
    float: left;
    }
    .checkbox {
    float: left;
    width: 98%;
    text-align: left;
    }
    .checkbox label {
    float: left;
    width: auto;
    margin: 0;
    }
    .checkbox input[type="checkbox"] {
    float: left;
    width: auto;
    margin: 4px 0;
    }
    .dl-horizontal.dd-horizontal > dd {
    width: 100%;
    text-align: left;
    }
    .text-left.check-radio{
        margin-top:20px;
    }
    </style>
<div class="page-title">
    <div>
        <h1>Holiday Master</h1>
        <ul class="breadcrumb side">
            <li><i class="fa fa-home fa-lg"></i></li>
            <li>create</li>
        </ul>
    </div>
</div>
<div class="flash-message">
    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
    @if(Session::has('alert-' . $msg))
    <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
    @endif
    @endforeach
</div>
<div class="clearix"></div>
<div class="col-md-12">
    <div class="card">
        <h3 class="card-title">Create</h3>
        <div class="card-body">
            @include('partials.alert')
            <?= Form::open(array('url' => route('holiday-master.store') ,'class' => 'form-horizontal' ,'files' => true)) ?>
            {{ session('msg') }}
            
            <div class="form-group">
                <label class="control-label col-sm-2" for="inputFull Name">Holiday</label>
                <div class="col-sm-8">
                    <?= Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' => 'Holiday']); ?>
                    <?= $errors->first('title',"<span class='text-danger'>:message</span>");?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8 col-md-offset-2">
                    <button type="submit" class="btn btn-primary submit" id="submit" name="save_button" value="save_new">Save & New</button>
                    <button type="submit" class="btn btn-primary submit" id="submit1" name="save_button" value="save_exit">Save & Exit</button>
                    <a href="<?= URL::route('holiday-master.index') ?>" class="btn btn-white btn-default"> Cancel</a>
                    
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@stop
@section('style')
 
   
@stop
@section('script')
    <script type="text/javascript">

    //     jQuery(document).ready(function() {
    //     $('form').submit(function(){
    //         $(this).find('button:submit').html('<i class="fa fa-spinner fa-spin"></i>').prop('disabled', true);
    //     });

    // });
    </script>

@include('partials.alert') 
@stop

resources/views/holiday-master/edit.blade.php
@extends('layout.layout')
@section('content')
<style type="text/css">
    .avtar{
    background-color: #fff;
    padding:20px 0;
    }
    .avtar button.btn-primary {
    float: none;
    width: 80%;
    margin: 20px auto;
    }
    .avtar form {
    float: none;
    width: 90%;
    margin: auto;
    }
    .profile-detail{
    width:100%;
    background-color: #fff;
    padding:20px 0;
    }
    .profile-detail .dl-horizontal, .profile-detail .dd-horizontal {
    margin: 10px 0;
    }
    .profile-detail label {
    float: right;
    font-size: 16px;
    margin: 19px 0;
    }
    .profile-detail .form-control {
    float: left;
    width: 98%;
    margin: 10px 0;
    }
    .profile-detail textarea {
    width: 98%;
    }
    .profile-detail button {
    float: left;
    }
    .checkbox {
    float: left;
    width: 98%;
    text-align: left;
    }
    .checkbox label {
    float: left;
    width: auto;
    margin: 0;
    }
    .checkbox input[type="checkbox"] {
    float: left;
    width: auto;
    margin: 4px 0;
    }
    .dl-horizontal.dd-horizontal > dd {
    width: 100%;
    text-align: left;
    }
    .text-left.check-radio{
        margin-top:20px;
    }
    </style>
<div class="page-title">
    <div>
        <h1>Holiday Master</h1>
        <ul class="breadcrumb side">
            <li><i class="fa fa-home fa-lg"></i></li>
            <li>Edit</li>
        </ul>
    </div>
</div>
<div class="flash-message">
    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
    @if(Session::has('alert-' . $msg))
    <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
    @endif
    @endforeach
</div>
<div class="clearix"></div>
<div class="col-md-12">
    <div class="card">
        <h3 class="card-title">Edit</h3>
        <div class="card-body">
            @include('partials.alert')
            <?= Form::model($holiday_master,['route'=>['holiday-master.update','id'=>$holiday_master->id], 'class' => 'form-horizontal','method'=>'put','files'=>true]) ?>
            {{ session('msg') }}
            
            <div class="form-group">
                <label class="control-label col-sm-2" for="inputFull Name">Holiday</label>
                <div class="col-sm-8">
                    <?= Form::text('title', $holiday_master->title, ['class' => 'form-control', 'placeholder' => 'Holiday']); ?>
                    <?= $errors->first('title',"<span class='text-danger'>:message</span>");?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8 col-md-offset-2">
                    <button type="submit" class="btn btn-primary" value="save_exit" name="save_button">Save & Exit</button>
                    <button type="submit" class="btn btn-primary" value="save" name="save_button">Save</button>
                    <a href="<?= URL::route('holiday-master.index') ?>" class="btn btn-white btn-default"> Cancel</a>
                    
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@stop
@section('style')
    <?= Html::style('css/bootstrap-fileupload.css') ?>
   
@stop
@section('script')

   
    <?= Html::script('js/bootstrap-fileupload.js') ?>
<!-- 
    <script type="text/javascript">

        

        jQuery(document).ready(function() {
        $('form').submit(function(){
            $(this).find('button:submit').html('<i class="fa fa-spinner fa-spin"></i>').prop('disabled', true);
        });

    });
    </script> -->
@include('partials.alert') 
@stop

resources/views/holiday-master/index.blade.php
@extends('layout.layout')
@section('content')
<div class="page-title">
    <div>
        <h1>Holidays</h1>

    </div>
    <div>
        @if(CheckPermission::isPermitted('holiday.create'))
            <a href="<?= URL::route('holiday-master.create') ?>"class="btn btn-primary btn-flat"><i class="fa fa-lg fa-plus"></i></a>
        @endif

       <!--  <a href="<?=URL::route('holiday.create')?>" class="btn btn-primary btn-flat"><i class="fa fa-lg fa-plus"></i></a> -->
        <!-- <a href="#" class="btn btn-info btn-flat"><i class="fa fa-lg fa-refresh"></i></a>
        <a id="delete" href="javascript:void(0)" class="btn btn-warning btn-flat"><i class="fa fa-lg fa-trash"></i></a> -->
    </div>
</div>
<div class="flash-message">
    @foreach (['danger', 'warning', 'success', 'info'] as $msg)
        @if(Session::has('alert-' . $msg))
            <p class="alert alert-{{ $msg }}">{{ Session::get('alert-' . $msg) }} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
        @endif
    @endforeach
</div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <table id="employee" class="table table-hover table-bordered" border="1 px" style="width:100%;">
                        <thead>
                            <tr>
                               
                                <th>Title</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop
@section('script')

<?= Html::script('asset/DataTables/media/js/jquery.dataTables.min.js') ?>
<?= Html::script('asset/DataTables/media/js/dataTables.bootstrap.min.js') ?>
<?= Html::script('asset/js/delete_script.js') ?>
<?= Html::script('asset/js/fnStandingRedraw.js') ?>
<script>
var token = "<?= csrf_token() ?>";
var title = "Are you sure to delete selected record(s)?";
var text = "You will not be able to recover this record";
var type = "warning";
var delete_path = "<?=URL::route('holiday-master.delete') ?>";
$(document).ready(function(){

    $('#employee').DataTable({

        "bProcessing" : true,
        "bServerSide" : true,
        "ajax"        :"<?= URL::route('holiday-master.index') ?>",
        "aaSorting": [
                       [0, "asc"]
                    ],
        "bPaginate": false,
        "aoColumns" : [
            { mData: 'title' ,bSortable:true},
            
            {   
                mData: null,
                sWidth: "10%",
                bSortable : false,
                mRender:function(v,t,o) {

                    var path = "<?= URL::route('holiday-master.edit',array('id'=>':id')) ?>";
                    var path_del = "<?= URL::route('holiday-master.delete',array('id'=>':id')) ?>";

                    path     = path.replace(':id',o['id']);
                    path_del = path_del.replace(':id',o['id']);

                    var extra_html  =   "<div class='btn-group pr5'>"
                                    +       "<a title='Edit' href='"+path+"'><i class='fa fa-edit'></i></a>|"
                                    +   "<a id='delete' href='javascript:void(0)' onclick=\"deleteRecord('"+delete_path+"','"+title+"','"+text+"','"+token+"','"+type+"',"+o['id']+")\" class='fa fa-fw fa-trash-o'></a>  "
                                    +   "</div>";
                    return extra_html;


                }

            }
        ],
    });

    $.ajaxSetup({
        statusCode: {
          401: function() {
            location.reload();
          }
        }
    });

});
</script>
@include('partials.alert')
@stop